
function conf = create(do_save)

%   CREATE -- Create the config file. 
%
%     Define editable properties of the config file here.
%
%     IN:
%       - `do_save` (logical) -- Indicate whether to save the created
%         config file. Default is `false`

if ( nargin < 1 ), do_save = false; end

const = sfix.config.constants();

conf = struct();

% ID
conf.(const.config_id) = true;

% PATHS
PATHS = struct();
PATHS.repositories = fileparts( sfix.util.get_project_folder() );
PATHS.data = fullfile( sfix.util.get_project_folder(), 'data' );
PATHS.images = fullfile( sfix.util.get_project_folder(), 'images' );

%	INTERFACE
INTERFACE = struct();
INTERFACE.stop_key = KbName( 'escape' );
INTERFACE.gaze_source_type = 'mouse';
INTERFACE.reward_output_type = 'none';
INTERFACE.skip_sync_tests = false;
INTERFACE.tracker_sync_interval = 1;
INTERFACE.allow_hide_mouse = false;
INTERFACE.save_data = false;

%	SCREEN
SCREEN = struct();

SCREEN.full_size = get( 0, 'screensize' );
SCREEN.index = 0;
SCREEN.background_color = [ 0 0 0 ];
SCREEN.rect = [ 0, 0, 400, 400 ];
SCREEN.calibration_rect = [ 0, 0, 400, 400 ];

%	TIMINGS
TIMINGS = struct();

time_in = struct();
time_in.new_trial = 0;
time_in.initial_fixation = 1;
time_in.randomized_fixation = 3;
time_in.error_timeout = 1;
time_in.task = inf;
time_in.iti = 1;
time_in.iti_range = [1, 2];
time_in.cs_presentation = 0.5;
time_in.cs_delay = 0.3;
time_in.cs_reward = 0.2;
time_in.image_presentation = 1;

TIMINGS.time_in = time_in;

%	STIMULI
STIMULI = struct();
STIMULI.setup = struct();

non_editable_properties = {{ 'placement', 'has_target', 'image_matrix' }};

STIMULI.setup.initial_fixation = struct( ...
    'class',            'Rect' ...
  , 'size',             [ 50, 50 ] ...
  , 'color',            [ 255, 255, 255 ] ...
  , 'position',         [ 0.5, 0.5 ] ...
  , 'placement',        'center' ...
  , 'has_target',       true ...
  , 'target_duration',  0.3 ...
  , 'target_padding',   0 ...
  , 'non_editable',     non_editable_properties ...
);

STIMULI.setup.randomized_fixation = struct( ...
    'class',            'Rect' ...
  , 'size',             [ 50, 50 ] ...
  , 'color',            [ 255, 255, 255 ] ...
  , 'position',         [ 0.5, 0.5 ] ...
  , 'placement',        'center' ...
  , 'has_target',       true ...
  , 'target_duration',  0.3 ...
  , 'target_padding',   0 ...
  , 'target_duration_range', [0.1, 0.5] ...
  , 'non_editable',     non_editable_properties ...
);


STIMULI.setup.cue_no_reward = struct( ...
    'class',            'Rect' ...
  , 'size',             [ 50, 50 ] ...
  , 'color',            [ 255, 0, 0 ] ...
  , 'position',         [ 0.5, 0.5 ] ...
  , 'placement',        'center' ...
  , 'has_target',       true ...
  , 'target_duration',  0.3 ...
  , 'target_padding',   0 ...
  , 'target_duration_range', [0.1, 0.5] ...
  , 'non_editable',     non_editable_properties ...
);

STIMULI.setup.cue_small_reward = struct( ...
    'class',            'Rect' ...
  , 'size',             [ 50, 50 ] ...
  , 'color',            [ 255, 0, 255 ] ...
  , 'position',         [ 0.5, 0.5 ] ...
  , 'placement',        'center' ...
  , 'has_target',       true ...
  , 'target_duration',  0.3 ...
  , 'target_padding',   0 ...
  , 'target_duration_range', [0.1, 0.5] ...
  , 'non_editable',     non_editable_properties ...
);

STIMULI.setup.cue_large_reward = struct( ...
    'class',            'Rect' ...
  , 'size',             [ 50, 50 ] ...
  , 'color',            [ 0, 0, 255 ] ...
  , 'position',         [ 0.5, 0.5 ] ...
  , 'placement',        'center' ...
  , 'has_target',       true ...
  , 'target_duration',  0.3 ...
  , 'target_padding',   0 ...
  , 'target_duration_range', [0.1, 0.5] ...
  , 'non_editable',     non_editable_properties ...
);

STIMULI.setup.image = struct( ...
    'class',            'Rect' ...
  , 'size',             [ 50, 50 ] ...
  , 'color',            [ 0, 0, 255 ] ...
  , 'position',         [ 0.5, 0.5 ] ...
  , 'placement',        'center' ...
  , 'has_target',       true ...
  , 'target_duration',  0.3 ...
  , 'target_padding',   0 ...
  , 'target_duration_range', [0.1, 0.5] ...
  , 'non_editable',     non_editable_properties ...
);

%	SERIAL
SERIAL = struct();
SERIAL.port = 'COM3';
SERIAL.channels = { 'A' };

% SIGNAL
SIGNAL = struct();
SIGNAL.analog_channel_m1x = 'ai0';
SIGNAL.analog_channel_m1y = 'ai1';
SIGNAL.analog_gaze_input_channel_indices_m1 = [1, 2];
SIGNAL.analog_gaze_input_channel_indices_m2 = [3, 4];

% REWARDS
REWARDS = struct();
REWARDS.fixation_trial = 0.1;
REWARDS.cs_small = 0.1;
REWARDS.cs_large = 0.2;

% EXPORT
conf.PATHS = PATHS;
conf.TIMINGS = TIMINGS;
conf.STIMULI = STIMULI;
conf.SCREEN = SCREEN;
conf.INTERFACE = INTERFACE;
conf.SERIAL = SERIAL;
conf.SIGNAL = SIGNAL;
conf.REWARDS = REWARDS;

if ( do_save )
  sfix.config.save( conf );
end

end