classdef Data < handle
  properties
    trial_type = 'cs_presentation';
    randomized_fixation_position = [0, 0];
    randomized_fixation_duration = nan;
    conditioned_reward_size_label = 'small';
    conditioned_reward_size = 0;
    image = [];
    image_filename = '';
    iti_duration = 0;
    event_times = struct( ...
      'new_trial', struct( ....
        'entry', nan ...
      ) ...
      , 'randomized_fixation', struct( ...
          'entry', nan ...
        , 'target_acquired', nan ...
        , 'target_entry', nan ...
      ) ...
      , 'cs_presentation', struct( ...
          'entry', nan ...
        , 'cs_onset', nan ...
      ) ...
      , 'cs_delay', struct( ...
          'entry', nan ...
      ) ...
      , 'cs_reward', struct( ...
          'entry', nan ...
      ) ...
      , 'image_presentation', struct( ...
          'entry', nan ...
        , 'image_onset', nan ...
      ) ...
    );
  end
end